### ISSUE TITLE
Tasks - March 9

### ISSUE THREAD

**Issue by vivekaxl** [ai-se/SuperCharger#3]
- [x] Why are the initial scores different?
- [x] Repeat the experiment 10 times
- [x] IQR for all the measures

**Comment by vivekaxl** [comment]
## Why are the initial scores different?

They are not different. It is just because of the  scale of the axises. 

![figure01_pom3a_igd](https://cloud.githubusercontent.com/assets/6147456/13648330/12119cda-e606-11e5-8f9d-b56403345622.png)

**Comment by timm** [comment]
i think if we draw on a linear, not log x axis, and draw from x= -100 we can see the initial peek

also, if we draw on a linear, not log y - axis, we;ll see a severe l-shape. i.e. not much improvement in anything

also ,really, do we can about an IGD difference 1 to 0.1? cause if we don't then what the heck. what is the epsilon on the raw score values between 1 to 0.1?

now if we DO care about 1 to 0.1 then note how the sway stuff makes it harder for the optimizer to find better? i.e. sway is counter-indicated since it does not give the optimizer enough diversity for subsequent reasonong.
